//! 在 mihomo 的 YAML 中维护一段带标记的托管区块。
//!
//! 控制器 API 无法创建 proxy-provider（`PUT /providers/proxies` 返回 405），
//! 所以订阅必须写进 `config.yaml`。为了避免解析别人的 YAML，本模块只替换自己
//! 用起止标记框住的那一段，文件其余部分按字节原样保留。

use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;

use anyhow::{bail, Context, Result};

use crate::client::Client;
use crate::settings::Subscription;

pub const BEGIN: &str = "# >>> clash-tui managed block >>>";
pub const END: &str = "# <<< clash-tui managed block <<<";
pub const RULE_BEGIN: &str = "# >>> clash-tui rule >>>";
pub const RULE_END: &str = "# <<< clash-tui rule <<<";

const MANAGED_KEYS: [&str; 2] = ["proxy-providers", "proxy-groups"];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Action {
    Created,
    Replaced,
    Unchanged,
}

impl Action {
    pub fn label(self) -> &'static str {
        match self {
            Action::Created => "创建",
            Action::Replaced => "更新",
            Action::Unchanged => "无变化",
        }
    }
}

fn valid_name(name: &str) -> bool {
    let bytes = name.as_bytes();
    if bytes.is_empty() || bytes.len() > 64 {
        return false;
    }
    let first = bytes[0];
    if !(first.is_ascii_alphanumeric()) {
        return false;
    }
    bytes[1..]
        .iter()
        .all(|b| b.is_ascii_alphanumeric() || *b == b'_' || *b == b'.' || *b == b'-')
}

fn quote(value: &str) -> Result<String> {
    if value.contains('\n') || value.contains('\r') {
        bail!("取值必须是单行");
    }
    Ok(format!("'{}'", value.replace('\'', "''")))
}

pub fn validate(items: &[Subscription]) -> Result<()> {
    let mut names: Vec<&str> = Vec::new();
    let mut groups: Vec<String> = Vec::new();
    for item in items {
        if !valid_name(&item.name) {
            bail!(
                "订阅名 {:?} 不合法：只能使用字母、数字、'.'、'_'、'-'",
                item.name
            );
        }
        if names.contains(&item.name.as_str()) {
            bail!("订阅名 {:?} 重复", item.name);
        }
        names.push(&item.name);
        if !(item.url.starts_with("http://") || item.url.starts_with("https://")) {
            bail!("订阅 {:?} 的链接必须以 http:// 或 https:// 开头", item.name);
        }
        if item.url.contains('\n') || item.url.contains('\r') || item.url.contains('\t') {
            bail!("订阅 {:?} 的链接必须是单行", item.name);
        }
        let group = item.group_name();
        if !valid_name(&group) {
            bail!("订阅 {:?} 的分组名 {:?} 不合法", item.name, group);
        }
        if groups.contains(&group) {
            bail!("分组名 {:?} 重复", group);
        }
        groups.push(group);
    }
    Ok(())
}

pub fn render_block(items: &[Subscription]) -> Result<String> {
    validate(items)?;
    let mut lines = vec![
        BEGIN.to_string(),
        "# Generated by clash-tui. Edits inside this block are overwritten.".to_string(),
    ];
    if !items.is_empty() {
        lines.push("proxy-providers:".to_string());
        for item in items {
            lines.push(format!("  {}:", item.name));
            lines.push("    type: http".to_string());
            lines.push(format!("    url: {}", quote(&item.url)?));
            lines.push(format!("    path: ./providers/{}.yaml", item.name));
            lines.push(format!("    interval: {}", item.interval));
            lines.push("    health-check:".to_string());
            lines.push("      enable: true".to_string());
            lines.push(format!("      url: {}", quote(&item.health_url)?));
            lines.push(format!("      interval: {}", item.health_interval));
        }
        lines.push("proxy-groups:".to_string());
        for item in items {
            lines.push(format!("  - name: {}", quote(&item.group_name())?));
            lines.push("    type: select".to_string());
            lines.push("    use:".to_string());
            lines.push(format!("      - {}", item.name));
        }
    }
    lines.push(END.to_string());
    Ok(format!("{}\n", lines.join("\n")))
}

fn block_span(text: &str) -> Result<Option<(usize, usize)>> {
    match text.find(BEGIN) {
        None => {
            if text.contains(END) {
                bail!("发现 {} 却没有 {}，请手动修复文件", END, BEGIN);
            }
            Ok(None)
        }
        Some(begin) => match text[begin..].find(END) {
            None => bail!("发现 {} 却没有 {}，请手动修复文件", BEGIN, END),
            Some(offset) => {
                let end = begin + offset + END.len();
                Ok(Some((begin, end)))
            }
        },
    }
}

fn replace_block(text: &str, block: &str) -> Result<(String, Action)> {
    match block_span(text)? {
        None => {
            let mut prefix = text.to_string();
            if !prefix.is_empty() && !prefix.ends_with('\n') {
                prefix.push('\n');
            }
            let separator = if prefix.is_empty() { "" } else { "\n" };
            Ok((
                format!("{prefix}{separator}{}", block.trim_end_matches('\n')),
                Action::Created,
            ))
        }
        Some((begin, end)) => {
            if text[begin..end] == *block.trim_end_matches('\n') {
                return Ok((text.to_string(), Action::Unchanged));
            }
            Ok((
                format!(
                    "{}{}{}",
                    &text[..begin],
                    block.trim_end_matches('\n'),
                    &text[end..]
                ),
                Action::Replaced,
            ))
        }
    }
}

fn top_level_key(line: &str) -> Option<&str> {
    if line.starts_with(' ') || line.starts_with('\t') || line.starts_with('#') {
        return None;
    }
    let (key, _) = line.split_once(':')?;
    if key.is_empty()
        || !key
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'_' || b == b'-')
    {
        return None;
    }
    Some(key)
}

fn top_level_keys(text: &str) -> Vec<String> {
    let mut keys = Vec::new();
    let mut inside = false;
    for line in text.lines() {
        let stripped = line.trim();
        if stripped == BEGIN {
            inside = true;
        } else if stripped == END {
            inside = false;
        } else if !inside {
            if let Some(key) = top_level_key(line) {
                keys.push(key.to_string());
            }
        }
    }
    keys
}

/// 在顶层 `rules:` 列表里插入/删除本工具的一条兜底规则。
pub fn set_rule(text: &str, target: Option<&str>) -> Result<String> {
    let mut lines: Vec<String> = text.split_inclusive('\n').map(|s| s.to_string()).collect();
    let body: Vec<String> = vec![
        format!("  {RULE_BEGIN}\n"),
        format!("  - MATCH,{}\n", target.unwrap_or_default()),
        format!("  {RULE_END}\n"),
    ];

    if let Some(index) = lines
        .iter()
        .position(|line| line.trim() == RULE_BEGIN)
    {
        let end = lines
            .iter()
            .skip(index)
            .position(|line| line.trim() == RULE_END)
            .map(|offset| index + offset)
            .context(format!("发现 {RULE_BEGIN} 却没有 {RULE_END}，请手动修复文件"))?;
        if target.is_none() {
            lines.drain(index..=end);
            return Ok(lines.concat());
        }
        let current: String = lines[index..=end].concat();
        let wanted: String = body.concat();
        if current == wanted {
            return Ok(text.to_string());
        }
        lines.splice(index..=end, body);
        return Ok(lines.concat());
    }

    if target.is_none() {
        return Ok(text.to_string());
    }

    if let Some(index) = lines.iter().position(|line| top_level_key(line) == Some("rules")) {
        let trimmed = lines[index].trim_end().to_string();
        if trimmed.ends_with("[]") {
            lines[index] = format!("{}\n", trimmed.trim_end_matches("[]").trim_end());
        }
        lines.splice(index + 1..index + 1, body);
        return Ok(lines.concat());
    }

    let mut suffix = text.to_string();
    if !suffix.is_empty() && !suffix.ends_with('\n') {
        suffix.push('\n');
    }
    let separator = if suffix.trim().is_empty() { "" } else { "\n" };
    Ok(format!(
        "{suffix}{separator}rules:\n{}",
        body.concat()
    ))
}

pub fn build(original: &str, items: &[Subscription], rule_target: Option<&str>) -> Result<(String, Action)> {
    let block = render_block(items)?;
    let (text, action) = replace_block(original, &block)?;
    let conflicts: Vec<String> = top_level_keys(&text)
        .into_iter()
        .filter(|k| MANAGED_KEYS.contains(&k.as_str()))
        .collect();
    if !conflicts.is_empty() {
        bail!(
            "{} 在托管块之外被重复定义；请把它们移入托管块或删除，否则 YAML 会出现重复键",
            conflicts.join("、")
        );
    }
    Ok((set_rule(&text, rule_target)?, action))
}

fn write_file(path: &Path, text: &str, mode: u32) -> Result<()> {
    fs::write(path, text).with_context(|| format!("无法写入 {}", path.display()))?;
    fs::set_permissions(path, fs::Permissions::from_mode(mode)).ok();
    Ok(())
}

/// 写入托管块，并在内核可达时热重载；内核拒绝则回滚文件。
pub async fn apply(
    config_path: &str,
    items: &[Subscription],
    rule_target: Option<&str>,
    client: Option<&Client>,
) -> Result<Action> {
    let path = Path::new(config_path);
    let original = fs::read_to_string(path)
        .with_context(|| format!("无法读取 {}", path.display()))?;
    let mode = fs::metadata(path)
        .map(|m| m.permissions().mode() & 0o777)
        .unwrap_or(0o600);
    let (text, action) = build(&original, items, rule_target)?;
    if action == Action::Unchanged && text == original {
        return Ok(Action::Unchanged);
    }

    let backup = format!("{}.bak", config_path);
    write_file(Path::new(&backup), &original, mode)?;
    write_file(path, &text, mode)?;

    let Some(client) = client else {
        return Ok(action);
    };
    match client.reload(config_path).await {
        Ok(()) => Ok(action),
        Err(error) => {
            write_file(path, &original, mode)?;
            let _ = client.reload(config_path).await;
            bail!("内核拒绝了新配置，文件已还原：{error}");
        }
    }
}
